In [1]:
import pandas as pd
df=pd.read_csv("newdataset.csv")
df

Unnamed: 0  BMDSTATS  RIAGENDR  RIDAGEYR     BMXWT     BHXHT    BMXLEG  \
0               0         1         2        13  0.165946  0.775050  0.660000   
1               1         1         1         2  0.047188  0.447395  0.704377   
2               2         1         2        29  0.381832  0.802605  0.741818   
3               3         1         2        18  0.296107  0.781563  0.774545   
4               4         1         1         2  0.388517  0.913327  0.729091   
...           ...       ...       ...       ...       ...       ...       ...   
13132       13132         1         1        11  0.427841  0.845190  0.829091   
13133       13133         1         2        12  0.060558  0.469439  0.704377   
13134       13134         1         1        64  0.090051  0.617735  0.704377   
13135       13135         1         2        12  0.312623  0.883768  0.763636   
13136       13136         1         2        43  0.234762  0.839178  0.747273   

        BOXARML   BMXARMC  BMXWAIST    BMXHIP  OUTMAL  
0      0.677355  0.351938  0.340267  0.453333       1  
1      0.372745  0.229457  0.219733  0.563755       1  
2      0.695391  0.555039  0.628800  0.672533       0  
3      0.723447  0.480620  0.487467  0.563755       0  
4      0.841683  0.592248  0.642133  0.577067       0  
...         ...       ...       ...       ...     ...  
13132  0.773547  0.520930  0.611733  0.629333       0  
13133  0.350701  0.244961  0.258133  0.563755       1  
13134  0.486974  0.286822  0.306667  0.563755       1  
13135  0.791583  0.486822  0.517867  0.532267       0  
13136  0.807615  0.452713  0.463467  0.482667       0  

[13137 rows x 12 columns]

In [2]:
df=df.drop(['Unnamed: 0'],axis=1)

In [3]:
import numpy as np

In [4]:
X= df[['BMDSTATS'	,'RIAGENDR',	'RIDAGEYR',	'BMXWT',	'BHXHT',	'BMXLEG',	'BOXARML',	'BMXARMC',	'BMXWAIST',	'BMXHIP']].values
X[0:10]

array([[1.00000000e+00, 2.00000000e+00, 1.30000000e+01, 1.65945733e-01,
        7.75050100e-01, 6.60000000e-01, 6.77354709e-01, 3.51937984e-01,
        3.40266667e-01, 4.53333333e-01],
       [1.00000000e+00, 1.00000000e+00, 2.00000000e+00, 4.71883602e-02,
        4.47394790e-01, 7.04376742e-01, 3.72745491e-01, 2.29457364e-01,
        2.19733333e-01, 5.63755337e-01],
       [1.00000000e+00, 2.00000000e+00, 2.90000000e+01, 3.81832481e-01,
        8.02605210e-01, 7.41818182e-01, 6.95390782e-01, 5.55038760e-01,
        6.28800000e-01, 6.72533333e-01],
       [1.00000000e+00, 2.00000000e+00, 1.80000000e+01, 2.96106960e-01,
        7.81563126e-01, 7.74545455e-01, 7.23446894e-01, 4.80620155e-01,
        4.87466667e-01, 5.63755337e-01],
       [1.00000000e+00, 1.00000000e+00, 2.00000000e+00, 3.88517499e-01,
        9.13326653e-01, 7.29090909e-01, 8.41683367e-01, 5.92248062e-01,
        6.42133333e-01, 5.77066667e-01],
       [1.00000000e+00, 1.00000000e+00, 4.90000000e+01, 2.92174597e-01,
   

In [5]:
y=df['OUTMAL'].values
y[0:10]

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 1])

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print('Train set :',X_train.shape,y_train.shape)
print('Test set :',X_test.shape,y_test.shape)

Train set : (10509, 10) (10509,)
Test set : (2628, 10) (2628,)


In [7]:
# SVM with kernel = linear
from sklearn.svm import SVC
classifier=SVC(kernel='linear',random_state=0)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [8]:
y_pred

array([1, 1, 0, ..., 0, 0, 0])

In [9]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("SVM'S accuracy",metrics.accuracy_score(y_test,y_pred))

SVM'S accuracy 0.9665144596651446


In [10]:
# SVM with kernel = rbf
from sklearn.svm import SVC
classifier=SVC(kernel='rbf',random_state=0)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
print("SVM'S accuracy",metrics.accuracy_score(y_test,y_pred))

SVM'S accuracy 0.819634703196347
